{"name": "FireBase_Verify PUT request successfully updates chatbot details -- @1.1 ", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_an_existing_chatbot_non_API_fields.py\", line 25, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Given FireBase_User sends PUT request to update chatbot details with chatbot_name \"New updated Name\", chatbot_description \"Updated through Automation suite\", and env_id \"f0b53f20-5ebe-4132-cbea-68725ef2c5c8\"", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_an_existing_chatbot_non_API_fields.py\", line 25, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "start": 1757691374068, "stop": 1757691374570}, {"name": "When FireBase_the user receives the response", "status": "skipped", "start": 1757691374574, "stop": 1757691374574}, {"name": "Then FireBase_the status code returned should be 200 for a successful request", "status": "skipped", "start": 1757691374574, "stop": 1757691374574}, {"name": "And FireBase_the response should contain the chatbot_id", "status": "skipped", "start": 1757691374574, "stop": 1757691374574}, {"name": "And FireBase_the status should be In_progress", "status": "skipped", "start": 1757691374574, "stop": 1757691374574}], "parameters": [{"name": "chatbot_name", "value": "New updated Name"}, {"name": "chatbot_description", "value": "Updated through Automation suite"}, {"name": "env_id", "value": "f0b53f20-5ebe-4132-cbea-68725ef2c5c8"}], "start": 1757691374067, "stop": 1757691374574, "uuid": "dcbe110f-172d-42b4-97c5-153533a31afd", "historyId": "e66b90ac10c35f6706faa0a7e60d3584", "fullName": "FireBase_Update Chatbot API: FireBase_Verify PUT request successfully updates chatbot details", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "FireBase_Update Chatbot API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "FireBase_Update Chatbot API"]}