{"name": "SQL Injection Attempt in PUT request for chatbot details -- @1.1 ", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_an_existing_chatbot_non_API_fields.py\", line 162, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "steps": [{"name": "Given FireBase_User sends request with chatbot_id \"' OR 1=1 --\", chatbot_name \"' OR 1=1 --\", chatbot_description \"' OR 1=1 --\", and env_id \"' OR 1=1 --\"", "status": "broken", "statusDetails": {"message": "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyD08yxn7V_YAfkAY8mKDTYjfKV_qoPrdRQ\n", "trace": "  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1991, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\FireBase_Update_an_existing_chatbot_non_API_fields.py\", line 162, in step_impl\n    id_token = get_firebase_id_token()\n               ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\utilities\\authentication.py\", line 16, in get_firebase_id_token\n    response.raise_for_status()  # Raise an error for non-2xx responses\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Noman\\PycharmProjects\\generativesecurity\\.venv\\Lib\\site-packages\\requests\\models.py\", line 1026, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n"}, "start": 1757682181812, "stop": 1757682182372}, {"name": "When FireBase_the user receives the response", "status": "skipped", "start": 1757682182377, "stop": 1757682182378}, {"name": "Then FireBase_the response should contain error variable The current request is matched to the defined", "status": "skipped", "start": 1757682182378, "stop": 1757682182378}, {"name": "And FireBase_the response should contain invalid input message", "status": "skipped", "start": 1757682182378, "stop": 1757682182378}], "parameters": [{"name": "chatbot_id", "value": "' OR 1=1 --"}, {"name": "chatbot_name", "value": "' OR 1=1 --"}, {"name": "chatbot_description", "value": "' OR 1=1 --"}, {"name": "env_id", "value": "' OR 1=1 --"}], "start": 1757682181810, "stop": 1757682182378, "uuid": "61776ab8-7631-4c4e-9f38-e50426daa498", "historyId": "af0dfe221f56914546bc72b3b540e267", "fullName": "Update Chatbot API: SQL Injection Attempt in PUT request for chatbot details", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Security"}, {"name": "tag", "value": "Test"}, {"name": "feature", "value": "Update Chatbot API"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Update Chatbot API"]}